// <auto-generated />
using System;
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516135643_a")]
    partial class a
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<int>("AuditoriaLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditoriaLogId"));

                    b.Property<string>("DatosJson")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsSospechoso")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("KioscoId")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoSospecha")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("AuditoriaLogId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EsSospechoso");

                    b.HasIndex("Fecha");

                    b.HasIndex("KioscoId");

                    b.ToTable("AuditoriaLog", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoriaID"));

                    b.Property<int>("KioscoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CategoriaID");

                    b.HasIndex("KioscoId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaID = 1,
                            KioscoId = 1,
                            Nombre = "Bebidas"
                        },
                        new
                        {
                            CategoriaID = 2,
                            KioscoId = 1,
                            Nombre = "Golosinas"
                        },
                        new
                        {
                            CategoriaID = 3,
                            KioscoId = 1,
                            Nombre = "Cigarrillos"
                        },
                        new
                        {
                            CategoriaID = 4,
                            KioscoId = 1,
                            Nombre = "Comida"
                        });
                });

            modelBuilder.Entity("Domain.Entities.CierreTurno", b =>
                {
                    b.Property<int>("CierreTurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CierreTurnoId"));

                    b.Property<int>("CantidadVentas")
                        .HasColumnType("integer");

                    b.Property<decimal>("Diferencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EfectivoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EfectivoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KioscoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoEsperado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoReal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("VirtualFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VirtualInicial")
                        .HasColumnType("numeric");

                    b.HasKey("CierreTurnoId");

                    b.HasIndex("TurnoId");

                    b.HasIndex("KioscoId", "Estado");

                    b.ToTable("CierresTurno");
                });

            modelBuilder.Entity("Domain.Entities.CierreTurnoEmpleado", b =>
                {
                    b.Property<int>("CierreTurnoId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.HasKey("CierreTurnoId", "EmpleadoId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("CierreTurnoEmpleado", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmpleadoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("boolean");

                    b.Property<int>("KioscoID")
                        .HasColumnType("integer");

                    b.Property<string>("Legajo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PIN")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int?>("UsuarioID")
                        .HasColumnType("integer");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("KioscoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Empleado", (string)null);

                    b.HasData(
                        new
                        {
                            EmpleadoId = 1,
                            Activo = true,
                            EsAdmin = true,
                            KioscoID = 1,
                            Legajo = "ADMIN001",
                            Nombre = "Kiosconeta24HS",
                            UsuarioID = 1
                        },
                        new
                        {
                            EmpleadoId = 2,
                            Activo = true,
                            EsAdmin = false,
                            KioscoID = 1,
                            Legajo = "EMP001",
                            Nombre = "Luchi",
                            PIN = "QTKFqtmpXhrIj8iA8M8G8/ql8bxK63p2oRpzrJTTHNM=",
                            Telefono = "1123456789"
                        },
                        new
                        {
                            EmpleadoId = 3,
                            Activo = true,
                            EsAdmin = false,
                            KioscoID = 1,
                            Legajo = "EMP002",
                            Nombre = "Brenda",
                            PIN = "D/4avRoIIVNTwjPW4AlhPpXuxCU4Mqdhryj/N6xaFQw=",
                            Telefono = "1198765432"
                        },
                        new
                        {
                            EmpleadoId = 4,
                            Activo = true,
                            EsAdmin = false,
                            KioscoID = 1,
                            Legajo = "EMP003",
                            Nombre = "Carlos López",
                            PIN = "iI3yWuNXckJKVgxxUqHeeURA4Opc/uYoKDM6RWpQbgU=",
                            Telefono = "1155443322"
                        });
                });

            modelBuilder.Entity("Domain.Entities.EmpleadoPermiso", b =>
                {
                    b.Property<int>("EmpleadoPermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmpleadoPermisoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("PermisoId")
                        .HasColumnType("integer");

                    b.HasKey("EmpleadoPermisoId");

                    b.HasIndex("PermisoId");

                    b.HasIndex("EmpleadoId", "PermisoId")
                        .IsUnique();

                    b.ToTable("EmpleadoPermiso", (string)null);

                    b.HasData(
                        new
                        {
                            EmpleadoPermisoId = -1,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 1
                        },
                        new
                        {
                            EmpleadoPermisoId = -2,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 2
                        },
                        new
                        {
                            EmpleadoPermisoId = -3,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 3
                        },
                        new
                        {
                            EmpleadoPermisoId = -4,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 4
                        },
                        new
                        {
                            EmpleadoPermisoId = -5,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 5
                        },
                        new
                        {
                            EmpleadoPermisoId = -6,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 6
                        },
                        new
                        {
                            EmpleadoPermisoId = -7,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 7
                        },
                        new
                        {
                            EmpleadoPermisoId = -8,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 8
                        },
                        new
                        {
                            EmpleadoPermisoId = -9,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 9
                        },
                        new
                        {
                            EmpleadoPermisoId = -10,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 10
                        },
                        new
                        {
                            EmpleadoPermisoId = -11,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 11
                        },
                        new
                        {
                            EmpleadoPermisoId = -12,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 12
                        },
                        new
                        {
                            EmpleadoPermisoId = -13,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 13
                        },
                        new
                        {
                            EmpleadoPermisoId = -14,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 14
                        },
                        new
                        {
                            EmpleadoPermisoId = -15,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 15
                        },
                        new
                        {
                            EmpleadoPermisoId = -16,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 16
                        },
                        new
                        {
                            EmpleadoPermisoId = -17,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 17
                        },
                        new
                        {
                            EmpleadoPermisoId = -18,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 18
                        },
                        new
                        {
                            EmpleadoPermisoId = -19,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 19
                        },
                        new
                        {
                            EmpleadoPermisoId = -20,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 20
                        },
                        new
                        {
                            EmpleadoPermisoId = -21,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 21
                        },
                        new
                        {
                            EmpleadoPermisoId = -22,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 22
                        },
                        new
                        {
                            EmpleadoPermisoId = -23,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 23
                        },
                        new
                        {
                            EmpleadoPermisoId = -24,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 24
                        },
                        new
                        {
                            EmpleadoPermisoId = -25,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 25
                        },
                        new
                        {
                            EmpleadoPermisoId = -26,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 26
                        },
                        new
                        {
                            EmpleadoPermisoId = -27,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 27
                        },
                        new
                        {
                            EmpleadoPermisoId = -28,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 28
                        },
                        new
                        {
                            EmpleadoPermisoId = -29,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 29
                        },
                        new
                        {
                            EmpleadoPermisoId = -30,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 30
                        },
                        new
                        {
                            EmpleadoPermisoId = -31,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 31
                        },
                        new
                        {
                            EmpleadoPermisoId = -32,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 32
                        },
                        new
                        {
                            EmpleadoPermisoId = -33,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 33
                        },
                        new
                        {
                            EmpleadoPermisoId = -34,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 34
                        },
                        new
                        {
                            EmpleadoPermisoId = -35,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 35
                        },
                        new
                        {
                            EmpleadoPermisoId = -36,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 36
                        },
                        new
                        {
                            EmpleadoPermisoId = -37,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 37
                        },
                        new
                        {
                            EmpleadoPermisoId = -38,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 38
                        },
                        new
                        {
                            EmpleadoPermisoId = -39,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 39
                        },
                        new
                        {
                            EmpleadoPermisoId = -40,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 40
                        },
                        new
                        {
                            EmpleadoPermisoId = -41,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 41
                        },
                        new
                        {
                            EmpleadoPermisoId = -42,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 42
                        },
                        new
                        {
                            EmpleadoPermisoId = -43,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 43
                        },
                        new
                        {
                            EmpleadoPermisoId = -44,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 44
                        },
                        new
                        {
                            EmpleadoPermisoId = -45,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 45
                        },
                        new
                        {
                            EmpleadoPermisoId = -46,
                            Activo = false,
                            EmpleadoId = 1,
                            FechaAsignacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermisoId = 46
                        });
                });

            modelBuilder.Entity("Domain.Entities.Gasto", b =>
                {
                    b.Property<int>("GastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GastoId"));

                    b.Property<int?>("CierreTurnoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("KioscoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoDeGastoId")
                        .HasColumnType("integer");

                    b.HasKey("GastoId");

                    b.HasIndex("CierreTurnoId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("Fecha");

                    b.HasIndex("KioscoId");

                    b.HasIndex("TipoDeGastoId");

                    b.ToTable("Gasto", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Kiosco", b =>
                {
                    b.Property<int>("KioscoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KioscoID"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("integer");

                    b.HasKey("KioscoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Kiosco", (string)null);

                    b.HasData(
                        new
                        {
                            KioscoID = 1,
                            Direccion = "845 2595",
                            Nombre = "Kiosconeta 1",
                            UsuarioID = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.MetodoDePago", b =>
                {
                    b.Property<int>("MetodoDePagoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MetodoDePagoID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MetodoDePagoID");

                    b.ToTable("MetodoDePago", (string)null);

                    b.HasData(
                        new
                        {
                            MetodoDePagoID = 1,
                            Nombre = "Efectivo"
                        },
                        new
                        {
                            MetodoDePagoID = 2,
                            Nombre = "Mercado Pago"
                        },
                        new
                        {
                            MetodoDePagoID = 3,
                            Nombre = "Débito"
                        });
                });

            modelBuilder.Entity("Domain.Entities.MovimientoCaja", b =>
                {
                    b.Property<int>("MovimientoCajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovimientoCajaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("KioscoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("MovimientoCajaId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("Fecha");

                    b.HasIndex("KioscoId");

                    b.ToTable("MovimientoCaja", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Permiso", b =>
                {
                    b.Property<int>("PermisoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermisoID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PermisoID");

                    b.ToTable("Permiso", (string)null);

                    b.HasData(
                        new
                        {
                            PermisoID = 1,
                            Descripcion = "Ver listado de productos",
                            Nombre = "productos.ver"
                        },
                        new
                        {
                            PermisoID = 2,
                            Descripcion = "Crear nuevos productos",
                            Nombre = "productos.crear"
                        },
                        new
                        {
                            PermisoID = 3,
                            Descripcion = "Editar productos existentes",
                            Nombre = "productos.editar"
                        },
                        new
                        {
                            PermisoID = 4,
                            Descripcion = "Eliminar productos",
                            Nombre = "productos.eliminar"
                        },
                        new
                        {
                            PermisoID = 5,
                            Descripcion = "Activar o desactivar productos",
                            Nombre = "productos.activar_desactivar"
                        },
                        new
                        {
                            PermisoID = 6,
                            Descripcion = "Ajustar stock manualmente",
                            Nombre = "productos.ajustar_stock"
                        },
                        new
                        {
                            PermisoID = 7,
                            Descripcion = "Ver productos con stock bajo",
                            Nombre = "productos.ver_stock_bajo"
                        },
                        new
                        {
                            PermisoID = 8,
                            Descripcion = "Editar precios de venta y costo",
                            Nombre = "productos.editar_precios"
                        },
                        new
                        {
                            PermisoID = 9,
                            Descripcion = "Ver categorías",
                            Nombre = "categorias.ver"
                        },
                        new
                        {
                            PermisoID = 10,
                            Descripcion = "Crear categorías",
                            Nombre = "categorias.crear"
                        },
                        new
                        {
                            PermisoID = 11,
                            Descripcion = "Editar categorías",
                            Nombre = "categorias.editar"
                        },
                        new
                        {
                            PermisoID = 12,
                            Descripcion = "Eliminar categorías",
                            Nombre = "categorias.eliminar"
                        },
                        new
                        {
                            PermisoID = 13,
                            Descripcion = "Crear ventas (usar POS)",
                            Nombre = "ventas.crear"
                        },
                        new
                        {
                            PermisoID = 14,
                            Descripcion = "Ver todas las ventas del kiosco",
                            Nombre = "ventas.ver_todas"
                        },
                        new
                        {
                            PermisoID = 15,
                            Descripcion = "Ver solo sus propias ventas",
                            Nombre = "ventas.ver_propias"
                        },
                        new
                        {
                            PermisoID = 16,
                            Descripcion = "Ver detalle completo de ventas",
                            Nombre = "ventas.ver_detalle"
                        },
                        new
                        {
                            PermisoID = 17,
                            Descripcion = "Anular ventas",
                            Nombre = "ventas.anular"
                        },
                        new
                        {
                            PermisoID = 18,
                            Descripcion = "Ver ventas por empleado",
                            Nombre = "ventas.ver_por_empleado"
                        },
                        new
                        {
                            PermisoID = 19,
                            Descripcion = "Registrar gastos",
                            Nombre = "gastos.crear"
                        },
                        new
                        {
                            PermisoID = 20,
                            Descripcion = "Ver todos los gastos",
                            Nombre = "gastos.ver_todos"
                        },
                        new
                        {
                            PermisoID = 21,
                            Descripcion = "Ver solo sus propios gastos",
                            Nombre = "gastos.ver_propios"
                        },
                        new
                        {
                            PermisoID = 22,
                            Descripcion = "Editar gastos",
                            Nombre = "gastos.editar"
                        },
                        new
                        {
                            PermisoID = 23,
                            Descripcion = "Eliminar gastos",
                            Nombre = "gastos.eliminar"
                        },
                        new
                        {
                            PermisoID = 24,
                            Descripcion = "Crear y editar tipos de gasto",
                            Nombre = "gastos.gestionar_tipos"
                        },
                        new
                        {
                            PermisoID = 25,
                            Descripcion = "Abrir turnos",
                            Nombre = "turnos.abrir"
                        },
                        new
                        {
                            PermisoID = 26,
                            Descripcion = "Cerrar turnos",
                            Nombre = "turnos.cerrar"
                        },
                        new
                        {
                            PermisoID = 27,
                            Descripcion = "Ver todos los turnos del kiosco",
                            Nombre = "turnos.ver_todos"
                        },
                        new
                        {
                            PermisoID = 28,
                            Descripcion = "Ver solo su turno actual",
                            Nombre = "turnos.ver_propio"
                        },
                        new
                        {
                            PermisoID = 29,
                            Descripcion = "Ver historial de turnos",
                            Nombre = "turnos.ver_historial"
                        },
                        new
                        {
                            PermisoID = 30,
                            Descripcion = "Ajustar diferencias en cierres",
                            Nombre = "turnos.ajustar"
                        },
                        new
                        {
                            PermisoID = 31,
                            Descripcion = "Ver listado de empleados",
                            Nombre = "empleados.ver"
                        },
                        new
                        {
                            PermisoID = 32,
                            Descripcion = "Crear nuevos empleados",
                            Nombre = "empleados.crear"
                        },
                        new
                        {
                            PermisoID = 33,
                            Descripcion = "Editar empleados",
                            Nombre = "empleados.editar"
                        },
                        new
                        {
                            PermisoID = 34,
                            Descripcion = "Eliminar empleados",
                            Nombre = "empleados.eliminar"
                        },
                        new
                        {
                            PermisoID = 35,
                            Descripcion = "Asignar y quitar permisos a empleados",
                            Nombre = "empleados.asignar_permisos"
                        },
                        new
                        {
                            PermisoID = 36,
                            Descripcion = "Ver estadísticas de rendimiento",
                            Nombre = "empleados.ver_rendimiento"
                        },
                        new
                        {
                            PermisoID = 37,
                            Descripcion = "Ver dashboard completo",
                            Nombre = "reportes.dashboard_completo"
                        },
                        new
                        {
                            PermisoID = 38,
                            Descripcion = "Ver dashboard básico del día",
                            Nombre = "reportes.dashboard_basico"
                        },
                        new
                        {
                            PermisoID = 39,
                            Descripcion = "Ver reportes de ventas",
                            Nombre = "reportes.ventas"
                        },
                        new
                        {
                            PermisoID = 40,
                            Descripcion = "Ver reportes de productos",
                            Nombre = "reportes.productos"
                        },
                        new
                        {
                            PermisoID = 41,
                            Descripcion = "Ver reportes financieros",
                            Nombre = "reportes.financiero"
                        },
                        new
                        {
                            PermisoID = 42,
                            Descripcion = "Ver métodos de pago",
                            Nombre = "metodos_pago.ver"
                        },
                        new
                        {
                            PermisoID = 43,
                            Descripcion = "Crear métodos de pago",
                            Nombre = "metodos_pago.crear"
                        },
                        new
                        {
                            PermisoID = 44,
                            Descripcion = "Editar métodos de pago",
                            Nombre = "metodos_pago.editar"
                        },
                        new
                        {
                            PermisoID = 47,
                            Descripcion = "Eliminar métodos de pago",
                            Nombre = "metodos_pago.eliminar"
                        },
                        new
                        {
                            PermisoID = 45,
                            Descripcion = "Configurar datos del kiosco",
                            Nombre = "configuracion.kiosco"
                        },
                        new
                        {
                            PermisoID = 46,
                            Descripcion = "Crear respaldos de datos",
                            Nombre = "configuracion.respaldos"
                        },
                        new
                        {
                            PermisoID = 48,
                            Descripcion = "Ver promociones del kiosco",
                            Nombre = "promociones.ver"
                        },
                        new
                        {
                            PermisoID = 49,
                            Descripcion = "Crear nuevas promociones",
                            Nombre = "promociones.crear"
                        },
                        new
                        {
                            PermisoID = 50,
                            Descripcion = "Activar, desactivar y eliminar promociones",
                            Nombre = "promociones.editar"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoBarra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Distribuidor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Imagen")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("KioscoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockActual")
                        .HasColumnType("integer");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer");

                    b.Property<bool>("Suelto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("ProductoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("KioscoId");

                    b.ToTable("Producto", (string)null);

                    b.HasData(
                        new
                        {
                            ProductoId = 3,
                            Activo = true,
                            CategoriaId = 1,
                            CodigoBarra = "7790310980316",
                            Descripcion = "Gaseosa Pepsi sabor original 500ml",
                            Distribuidor = "PepsiCo",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Imagen = "",
                            KioscoId = 1,
                            Nombre = "Pepsi 500ml",
                            PrecioCosto = 950m,
                            PrecioVenta = 1800m,
                            StockActual = 40,
                            StockMinimo = 10,
                            Suelto = false
                        },
                        new
                        {
                            ProductoId = 4,
                            Activo = true,
                            CategoriaId = 1,
                            CodigoBarra = "7790895001090",
                            Descripcion = "Gaseosa Sprite lima-limón 500ml",
                            Distribuidor = "Coca-Cola FEMSA",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Imagen = "",
                            KioscoId = 1,
                            Nombre = "Sprite 500ml",
                            PrecioCosto = 950m,
                            PrecioVenta = 1800m,
                            StockActual = 35,
                            StockMinimo = 8,
                            Suelto = false
                        },
                        new
                        {
                            ProductoId = 5,
                            Activo = true,
                            CategoriaId = 1,
                            CodigoBarra = "7790895001083",
                            Descripcion = "Gaseosa Fanta sabor naranja 500ml",
                            Distribuidor = "Coca-Cola FEMSA",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Imagen = "",
                            KioscoId = 1,
                            Nombre = "Fanta Naranja 500ml",
                            PrecioCosto = 950m,
                            PrecioVenta = 1800m,
                            StockActual = 30,
                            StockMinimo = 8,
                            Suelto = false
                        },
                        new
                        {
                            ProductoId = 6,
                            Activo = true,
                            CategoriaId = 1,
                            CodigoBarra = "7790310980323",
                            Descripcion = "Gaseosa 7UP lima-limón 500ml",
                            Distribuidor = "PepsiCo",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Imagen = "",
                            KioscoId = 1,
                            Nombre = "7UP 500ml",
                            PrecioCosto = 950m,
                            PrecioVenta = 1800m,
                            StockActual = 25,
                            StockMinimo = 6,
                            Suelto = false
                        },
                        new
                        {
                            ProductoId = 7,
                            Activo = true,
                            CategoriaId = 1,
                            CodigoBarra = "7798062541016",
                            Descripcion = "Agua mineral sin gas 500ml",
                            Distribuidor = "Danone",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Imagen = "",
                            KioscoId = 1,
                            Nombre = "Agua Villavicencio 500ml",
                            PrecioCosto = 600m,
                            PrecioVenta = 1200m,
                            StockActual = 60,
                            StockMinimo = 15,
                            Suelto = false
                        },
                        new
                        {
                            ProductoId = 8,
                            Activo = true,
                            CategoriaId = 1,
                            CodigoBarra = "7791813001147",
                            Descripcion = "Agua mineral sin gas Ser 500ml",
                            Distribuidor = "PepsiCo",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Imagen = "",
                            KioscoId = 1,
                            Nombre = "Agua Ser 500ml",
                            PrecioCosto = 550m,
                            PrecioVenta = 1100m,
                            StockActual = 50,
                            StockMinimo = 12,
                            Suelto = false
                        },
                        new
                        {
                            ProductoId = 9,
                            Activo = true,
                            CategoriaId = 1,
                            CodigoBarra = "5099337012015",
                            Descripcion = "Bebida energizante Monster original lata 473ml",
                            Distribuidor = "Coca-Cola FEMSA",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Imagen = "",
                            KioscoId = 1,
                            Nombre = "Monster Energy Original 473ml",
                            PrecioCosto = 2200m,
                            PrecioVenta = 3800m,
                            StockActual = 24,
                            StockMinimo = 6,
                            Suelto = false
                        },
                        new
                        {
                            ProductoId = 10,
                            Activo = true,
                            CategoriaId = 1,
                            CodigoBarra = "9002490100070",
                            Descripcion = "Bebida energizante Red Bull lata 250ml",
                            Distribuidor = "Red Bull",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Imagen = "",
                            KioscoId = 1,
                            Nombre = "Red Bull 250ml",
                            PrecioCosto = 2500m,
                            PrecioVenta = 4200m,
                            StockActual = 18,
                            StockMinimo = 6,
                            Suelto = false
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProductoVenta", b =>
                {
                    b.Property<int>("ProductoVentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductoVentaId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("ProductoVentaId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("ProductoVenta", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Promocion", b =>
                {
                    b.Property<int>("PromocionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PromocionId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int?>("CantidadMinimaDescuento")
                        .HasColumnType("integer");

                    b.Property<int?>("CantidadPaga")
                        .HasColumnType("integer");

                    b.Property<int?>("CantidadRequerida")
                        .HasColumnType("integer");

                    b.Property<int?>("CategoriaIdPorcentaje")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("FechaDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KioscoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("PorcentajeDescuento")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PrecioCombo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductoIdCantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductoIdPorcentaje")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("PromocionId");

                    b.HasIndex("Activa");

                    b.HasIndex("CategoriaIdPorcentaje");

                    b.HasIndex("KioscoId");

                    b.HasIndex("ProductoIdCantidad");

                    b.HasIndex("ProductoIdPorcentaje");

                    b.ToTable("Promocion", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PromocionProducto", b =>
                {
                    b.Property<int>("PromocionProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PromocionProductoId"));

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("PromocionId")
                        .HasColumnType("integer");

                    b.HasKey("PromocionProductoId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("PromocionId");

                    b.ToTable("PromocionProducto", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SaldoCaja", b =>
                {
                    b.Property<int>("SaldoCajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SaldoCajaId"));

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("KioscoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaldoCajaId");

                    b.HasIndex("KioscoId")
                        .IsUnique();

                    b.ToTable("SaldoCaja", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Turno", b =>
                {
                    b.Property<int>("TurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TurnoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TurnoId");

                    b.ToTable("Turno", (string)null);

                    b.HasData(
                        new
                        {
                            TurnoId = 1,
                            Nombre = "Mañana"
                        },
                        new
                        {
                            TurnoId = 2,
                            Nombre = "Tarde"
                        },
                        new
                        {
                            TurnoId = 3,
                            Nombre = "Noche"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioID = 1,
                            Email = "admin@kiosconeta.com",
                            Nombre = "Admin",
                            Password = "$2a$11$Z66rXj1RWhDZD7977zpc.umjnKr17GY2GEin/ceL8.revuuSOIpjq"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Venta", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VentaId"));

                    b.Property<bool>("Anulada")
                        .HasColumnType("boolean");

                    b.Property<int>("CierreTurnoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Descuento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Detalles")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroVenta")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.HasKey("VentaId");

                    b.HasIndex("CierreTurnoId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("Fecha");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("TurnoId");

                    b.ToTable("Venta", (string)null);
                });

            modelBuilder.Entity("NumeradorVenta", b =>
                {
                    b.Property<int>("NumeradorVentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumeradorVentaId"));

                    b.Property<int>("KioscoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UltimoNumero")
                        .HasColumnType("integer");

                    b.HasKey("NumeradorVentaId");

                    b.HasIndex("KioscoId")
                        .IsUnique();

                    b.ToTable("NumeradoresVenta", (string)null);
                });

            modelBuilder.Entity("TipoDeGasto", b =>
                {
                    b.Property<int>("TipoDeGastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoDeGastoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("KioscoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TipoDeGastoId");

                    b.HasIndex("KioscoId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoDeGasto", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AuditoriaLog", b =>
                {
                    b.HasOne("Domain.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Kiosco", "Kiosco")
                        .WithMany()
                        .HasForeignKey("KioscoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Kiosco");
                });

            modelBuilder.Entity("Domain.Entities.Categoria", b =>
                {
                    b.HasOne("Domain.Entities.Kiosco", "Kiosco")
                        .WithMany()
                        .HasForeignKey("KioscoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Kiosco");
                });

            modelBuilder.Entity("Domain.Entities.CierreTurno", b =>
                {
                    b.HasOne("Domain.Entities.Kiosco", "Kiosco")
                        .WithMany("CierreTurnos")
                        .HasForeignKey("KioscoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kiosco");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Domain.Entities.CierreTurnoEmpleado", b =>
                {
                    b.HasOne("Domain.Entities.CierreTurno", "CierreTurno")
                        .WithMany("CierreTurnoEmpleados")
                        .HasForeignKey("CierreTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Empleado", "Empleado")
                        .WithMany("CierreTurnoEmpleados")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CierreTurno");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Domain.Entities.Empleado", b =>
                {
                    b.HasOne("Domain.Entities.Kiosco", "Kiosco")
                        .WithMany("Empleados")
                        .HasForeignKey("KioscoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("Empleados")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Kiosco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.EmpleadoPermiso", b =>
                {
                    b.HasOne("Domain.Entities.Empleado", "Empleado")
                        .WithMany("EmpleadoPermisos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Permiso", "Permiso")
                        .WithMany("EmpleadoPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Permiso");
                });

            modelBuilder.Entity("Domain.Entities.Gasto", b =>
                {
                    b.HasOne("Domain.Entities.CierreTurno", "CierreTurno")
                        .WithMany()
                        .HasForeignKey("CierreTurnoId");

                    b.HasOne("Domain.Entities.Empleado", "Empleado")
                        .WithMany("Gastos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Kiosco", "Kiosco")
                        .WithMany("Gastos")
                        .HasForeignKey("KioscoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TipoDeGasto", "TipoDeGasto")
                        .WithMany("Gastos")
                        .HasForeignKey("TipoDeGastoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CierreTurno");

                    b.Navigation("Empleado");

                    b.Navigation("Kiosco");

                    b.Navigation("TipoDeGasto");
                });

            modelBuilder.Entity("Domain.Entities.Kiosco", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("Kioscos")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.MovimientoCaja", b =>
                {
                    b.HasOne("Domain.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Kiosco", "Kiosco")
                        .WithMany()
                        .HasForeignKey("KioscoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Kiosco");
                });

            modelBuilder.Entity("Domain.Entities.Producto", b =>
                {
                    b.HasOne("Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Kiosco", "Kiosco")
                        .WithMany()
                        .HasForeignKey("KioscoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Kiosco");
                });

            modelBuilder.Entity("Domain.Entities.ProductoVenta", b =>
                {
                    b.HasOne("Domain.Entities.Producto", "Producto")
                        .WithMany("ProductoVentas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Venta", "Venta")
                        .WithMany("ProductoVentas")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Domain.Entities.Promocion", b =>
                {
                    b.HasOne("Domain.Entities.Categoria", "CategoriaPorcentaje")
                        .WithMany()
                        .HasForeignKey("CategoriaIdPorcentaje")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.Kiosco", "Kiosco")
                        .WithMany()
                        .HasForeignKey("KioscoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Producto", "ProductoCantidad")
                        .WithMany()
                        .HasForeignKey("ProductoIdCantidad")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.Producto", "ProductoPorcentaje")
                        .WithMany()
                        .HasForeignKey("ProductoIdPorcentaje")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CategoriaPorcentaje");

                    b.Navigation("Kiosco");

                    b.Navigation("ProductoCantidad");

                    b.Navigation("ProductoPorcentaje");
                });

            modelBuilder.Entity("Domain.Entities.PromocionProducto", b =>
                {
                    b.HasOne("Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Promocion", "Promocion")
                        .WithMany("PromocionProductos")
                        .HasForeignKey("PromocionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Promocion");
                });

            modelBuilder.Entity("Domain.Entities.SaldoCaja", b =>
                {
                    b.HasOne("Domain.Entities.Kiosco", "Kiosco")
                        .WithMany()
                        .HasForeignKey("KioscoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kiosco");
                });

            modelBuilder.Entity("Domain.Entities.Venta", b =>
                {
                    b.HasOne("Domain.Entities.CierreTurno", "CierreTurno")
                        .WithMany("Ventas")
                        .HasForeignKey("CierreTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Empleado", "Empleado")
                        .WithMany("Ventas")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.MetodoDePago", "MetodoPago")
                        .WithMany("Ventas")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Turno", "Turno")
                        .WithMany("Ventas")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CierreTurno");

                    b.Navigation("Empleado");

                    b.Navigation("MetodoPago");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("NumeradorVenta", b =>
                {
                    b.HasOne("Domain.Entities.Kiosco", "Kiosco")
                        .WithOne("NumeradorVenta")
                        .HasForeignKey("NumeradorVenta", "KioscoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kiosco");
                });

            modelBuilder.Entity("TipoDeGasto", b =>
                {
                    b.HasOne("Domain.Entities.Kiosco", "Kiosco")
                        .WithMany()
                        .HasForeignKey("KioscoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kiosco");
                });

            modelBuilder.Entity("Domain.Entities.CierreTurno", b =>
                {
                    b.Navigation("CierreTurnoEmpleados");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Domain.Entities.Empleado", b =>
                {
                    b.Navigation("CierreTurnoEmpleados");

                    b.Navigation("EmpleadoPermisos");

                    b.Navigation("Gastos");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Domain.Entities.Kiosco", b =>
                {
                    b.Navigation("CierreTurnos");

                    b.Navigation("Empleados");

                    b.Navigation("Gastos");

                    b.Navigation("NumeradorVenta")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.MetodoDePago", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Domain.Entities.Permiso", b =>
                {
                    b.Navigation("EmpleadoPermisos");
                });

            modelBuilder.Entity("Domain.Entities.Producto", b =>
                {
                    b.Navigation("ProductoVentas");
                });

            modelBuilder.Entity("Domain.Entities.Promocion", b =>
                {
                    b.Navigation("PromocionProductos");
                });

            modelBuilder.Entity("Domain.Entities.Turno", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("Kioscos");
                });

            modelBuilder.Entity("Domain.Entities.Venta", b =>
                {
                    b.Navigation("ProductoVentas");
                });

            modelBuilder.Entity("TipoDeGasto", b =>
                {
                    b.Navigation("Gastos");
                });
#pragma warning restore 612, 618
        }
    }
}
